version: '3.10'

services:
  fastapi-app:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - dev.env
    ports:
      - "5050:5050"

  postgres-db:
    container_name: postgres-db
    image: postgres:13.4-alpine
    restart: on-failure
    env_file:
      - dev.env

