version: '0.0.1'

services:
  fastapi-app:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - dev.env
    ports:
      - "5050:5050"
    environment:
      - POETRY_HOME=/opt/poetry
    volumes:
      - .:/opt/app
    command: ["python", "manage.py", "run"]
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:13.4-alpine
    restart: on-failure
    env_file:
      - dev.env
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

volumes:
    fastapi-postgres-volume:
